### ISSUE TITLE
Run NuScenes Driving Dataset

### ISSUE THREAD

**Issue by x2ss** [jayLEE0301/vq_bet_official#6]
Hi! 

Thank you for sharing this excellent work. 

I'm interested in using the NuScenes driving dataset, but I can't locate any guides. 

Could you please give me some advice?

Thank you and best regards!

**Comment by jayLEE0301** [comment]
Sorry for the late reply.

You could find how we modified vq-bet for NuScenes driving task in the last page of Appendix (https://arxiv.org/pdf/2403.03181)
and also, we downloaded and used pre-processed data from GPT-Driver (https://github.com/PointsCoder/GPT-Driver)

Thank you!

**Comment by x2ss** [comment]
> Sorry for the late reply.
> 
> You could find how we modified vq-bet for NuScenes driving task in the last page of Appendix (https://arxiv.org/pdf/2403.03181) and also, we downloaded and used pre-processed data from GPT-Driver (https://github.com/PointsCoder/GPT-Driver)
> 
> Thank you!

Thank you for your response. 

I wonder if there is any code related to the NuScenes Driving Dataset on this Repository? 

Thank you and best regards!

**Comment by jayLEE0301** [comment]
There's no some code for NuScenes Driving Dataset, but the only modification I did on GPT-Driver pre-processed data is reordering the objects in the order of distance from the agent, and extracting current pose / future traj / adding one-hot object class.

I modified gpt-driver/prompt_message.py, gpt-driver/create_data.py,  and gpt-driver/create_data_uniad.py

Thank you
Seungjae.

**Comment by x2ss** [comment]
> There's no some code for NuScenes Driving Dataset, but the only modification I did on GPT-Driver pre-processed data is reordering the objects in the order of distance from the agent, and extracting current pose / future traj / adding one-hot object class.
> 
> I modified gpt-driver/prompt_message.py, gpt-driver/create_data.py, and gpt-driver/create_data_uniad.py
> 
> Thank you Seungjae.

Thanks for your kind replay, it helps a lot.

**Comment by dichencd** [comment]
Thanks for the excellent work! I have some follow-up questions: You mentioned using **future** traj from GPT-Driver in vqbet. I wonder 
1. Whether the diffusion model based trajectory model also consumes the future trajectories?
2. Have you tried using only historical trajectories of other agents in the driving task since future trajectories are not observable in reality?

Thank you very much!
