### ISSUE TITLE
Why using torch.multinomial in probs select

### ISSUE THREAD

**Issue by hellollw** [jayLEE0301/vq_bet_official#7]
Hello, I find you using torch.multinomial in choosing the cbet_probs indices. I'm confused about this, torch.multinomial is sampled with  probability distribution. Why not using the max probs one as indices? 
```python
cbet_probs = torch.softmax(cbet_logits, dim=-1)
NT, G, choices = cbet_probs.shape
sampled_centers = einops.rearrange(
    torch.multinomial(cbet_probs.view(-1, choices), num_samples=1),
    "(NT G) 1 -> NT G",
    NT=NT,
)
```

**Comment by notmahi** [comment]
Hi @hellollw! One of the goals of VQ-BeT is to learn a multi-modal policy that has coverage of all possible demonstrated behavior, and not just the highest probability ones. That's why we sample from the possible actions rather than just picking the max probability action bin.
